### PR TITLE
fix: additional chars support in headers

### PR DESCRIPTION
**Pull request by SkeLLLa**
Adds support for numbers and `/` in headers comments in ~A section

Related to #15

### CODE REVIEW

**Comment by SkeLLLa** [comment]
@iykekings what do you think is it enough to cover all possible headers variants, or should I add something else to regex?

**Comment by iykekings** [comment]
LGTM

**Comment by SkeLLLa** [comment]
Updated regex according to https://github.com/laslibs/las-js/issues/15#issuecomment-657492249

**Comment by iykekings** [comment]
This is perfect...merging

**Pull request merged**
